name: mamkait

dependencies:
  - base == 4.*
  - containers
  - mtl
  - text
  - text-icu
  - tuple
  - bimap

library:
  source-dirs: src/
  exposed-modules:
  - Mamkait.Scratch
  - Mamkait.Error
  - Mamkait.Phonology
  - Mamkait.Grammar

executables:
  console:
    main: Main.hs
    source-dirs: console
    dependencies:
    - mamkait

tests:
  spec:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - mamkait
      - tasty
      - tasty-hunit

ghc-options:
  - -O2
  - -threaded
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-type-defaults

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
